#!/usr/bin/bash

# Apply overclocking parameters to my GPUs.


if [ $# -ne 1 ]; then
    echo "gpu-overclocker takes exactly one argument (the name of the tuning profile)"
    exit 1
fi

case $1 in
    default)
        echo -e "'$1' = STOCK SETTINGS\n"
        # Default power limit and clock offsets for RTX 2080ti
        sudo nvidia-smi -i 0 -pl 260
        sudo nvidia-smi -i 1 -pl 260
        nvidia-settings -a "[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=0"
        nvidia-settings -a "[gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels=0"
        nvidia-settings -a "[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=0"
        nvidia-settings -a "[gpu:1]/GPUMemoryTransferRateOffsetAllPerformanceLevels=0"
        # Automatic fan speed control
        nvidia-settings -a "[gpu:0]/GPUFanControlState=0"
        nvidia-settings -a "[gpu:1]/GPUFanControlState=0"
        ;;

    mining)
        echo -e "'$1' = ETHEREUM MINING SETTINGS\n"
        # Reduce power limit to minimise electricity cost
        sudo nvidia-smi -i 0 -pl 140
        sudo nvidia-smi -i 1 -pl 140
        # Decrease core clock
        nvidia-settings -a "[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=100"
        nvidia-settings -a "[gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels=100"
        # Increase memory clock
        nvidia-settings -a "[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=1800"
        nvidia-settings -a "[gpu:1]/GPUMemoryTransferRateOffsetAllPerformanceLevels=1800"
        # Manual fan control (fixed speed)
        nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=75"
        nvidia-settings -a "[gpu:1]/GPUFanControlState=1" -a "[fan:1]/GPUTargetFanSpeed=75"
        ;;

    *)
        echo "'$1' is not a recognised profile name! Aborting..."
        ;;
esac
